Repository perlin-network/wavelet-client-js, pull requests merged in 2019-07, with the labels that each got.

#1 Add Babel transform to support BigInt.
  dist/wavelet-client.umd.js
  package.json
  rollup.config.js
  yarn.lock
Labels: enhancement

#2 Added JSBI BigInt polyfill and removed Babel BigInt transform.
  .babelrc
  README.md
  dist/wavelet-client.cjs.js
  dist/wavelet-client.esm.js
  dist/wavelet-client.umd.js
  package.json
  rollup.config.js
  src/main.js
  test/test.js
  yarn.lock
Labels: bug, enhancement

#3 Parse polled batches of data from websocket endpoints.
  dist/wavelet-client.cjs.js
  dist/wavelet-client.esm.js
  dist/wavelet-client.umd.js
  src/main.js
Labels: enhancement

#4 Rebuild UMD and add missing core-js@2 dependency.
  dist/wavelet-client.umd.js
  package.json
  yarn.lock
Labels: enhancement

#5 Fix parseTransaction() to use payload argument correctly.
  dist/wavelet-client.cjs.js
  dist/wavelet-client.esm.js
  dist/wavelet-client.umd.js
  src/main.js
Labels: bug

#6 Fix errors when using browser-native BigInt, and automate builds on npm.
  .gitignore
  dist/wavelet-client.cjs.js
  dist/wavelet-client.esm.js
  dist/wavelet-client.umd.js
  package.json
  src/main.js
Labels: enhancement

#7 Add sender info to smart contract simulations.
  src/main.js
Labels: enhancement

#8 Add npm metadata.
  package.json
Labels: documentation

#9 Small fix and README update.
  README.md
  package.json
Labels: bug
